<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ticket extends \Application\Entity\Ticket implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketId', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketQuantity', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketInitialQuantity', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketLot', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketPrice', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketCreatedAt', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketUpdatedAt', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'event', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'carts'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketId', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketQuantity', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketInitialQuantity', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketLot', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketPrice', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketCreatedAt', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'ticketUpdatedAt', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'event', '' . "\0" . 'Application\\Entity\\Ticket' . "\0" . 'carts'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ticket $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTicketId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getTicketId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketId', []);

        return parent::getTicketId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketId($ticketId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketId', [$ticketId]);

        return parent::setTicketId($ticketId);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketQuantity', []);

        return parent::getTicketQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketQuantity($ticketQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketQuantity', [$ticketQuantity]);

        return parent::setTicketQuantity($ticketQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketInitialQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketInitialQuantity', []);

        return parent::getTicketInitialQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketInitialQuantity($ticketInitialQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketInitialQuantity', [$ticketInitialQuantity]);

        return parent::setTicketInitialQuantity($ticketInitialQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketLot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketLot', []);

        return parent::getTicketLot();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketLot($ticketLot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketLot', [$ticketLot]);

        return parent::setTicketLot($ticketLot);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketPrice', []);

        return parent::getTicketPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormattedTicketPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormattedTicketPrice', []);

        return parent::getFormattedTicketPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormattedTicketPrice($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormattedTicketPrice', [$value]);

        return parent::setFormattedTicketPrice($value);
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketPrice($ticketPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketPrice', [$ticketPrice]);

        return parent::setTicketPrice($ticketPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketCreatedAt', []);

        return parent::getTicketCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketCreatedAt($ticketCreatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketCreatedAt', [$ticketCreatedAt]);

        return parent::setTicketCreatedAt($ticketCreatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketUpdatedAt', []);

        return parent::getTicketUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketUpdatedAt', []);

        return parent::setTicketUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvent', []);

        return parent::getEvent();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvent($event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvent', [$event]);

        return parent::setEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarts', []);

        return parent::getCarts();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarts($carts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarts', [$carts]);

        return parent::setCarts($carts);
    }

}
