<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <h1>Lista de Eventos</h1>
            </div>
        </div>
        <div class="row">
            <?php foreach ($this->events as $event) : ?>
                <a href="<?php echo $this->url('root', ['controller' => 'index', 'action' => 'detail', 'id' => $event->getEventId()]) ?>">
                    <div class="col-sm-12 col-md-6 col-lg-3">
                        <div class="event">
                            <div class="event-content">
                                <h2><?php echo $event->getEventName() ?></h2>
                                <p><?php echo $event->getEventExcerpt() ?></p>
                                <p><span>Início:</span> <?php echo $event->getEventStartAt()->format("d/m/Y H:i") ?></p>
                                <p><span>Fim:</span> <?php echo $event->getEventFinishAt()->format("d/m/Y H:i") ?></p>
                            </div>
                            <div class="lot-content">
                                <?php foreach ($event->getTickets() as $ticket) : ?>
                                    <h3><?php echo $ticket->getTicketLot() ?></h3>
                                    <p><span>Tickets:</span> <?php echo $ticket->getTicketQuantity() ?>
                                        de <?php echo $ticket->getTicketInitialQuantity() ?></p>
                                    <p><span>Preço:</span> <?php echo $ticket->getFormattedTicketPrice() ?></p>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
</div>